name: Go

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: go build -v ./...
    
    - name: Install golint
      run: go get -u golang.org/x/lint/golint
    
    - name: Lint
      run: if [ "$(golint ./...)" -gt 0 ]; then exit 1; fi
      
    - name: Format
      env: 
        GO111MODULE: off
      run: if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then exit 1; fi

    - name: Test
      run: go test -v -coverprofile=coverage.out ./... 
    
    - name: Install goveralls
      env:
        GO111MODULE: off
      run: go get github.com/mattn/goveralls
      
    - name: Send coverage
      env:
        COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: goveralls -coverprofile=coverage.out -service=github
  

      
